%dev.quarkus.dev-ui.hosts=user2-quarkus-workshop-index-webpage.apps.cluster-kn5fw.dynamic2.redhatworkshops.io

# configure your datasource
%dev.quarkus.http.host=0.0.0.0
%dev.quarkus.http.port=8080
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=*
%dev.quarkus.dev-ui.cors.enabled=false
%dev.quarkus.kafka.devservices.enabled=false
%dev.quarkus.datasource.devservices.volumes."/"=/var/lib/postgresql/

%test.quarkus.datasource.devservices.volumes."/"=/var/lib/postgresql/

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-database/person
%prod.quarkus.datasource.jdbc.driver=org.postgresql.Driver
%prod.quarkus.hibernate-orm.sql-load-script=import.sql
%prod.quarkus.datasource.username=sa
%prod.quarkus.datasource.password=sa
%prod.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.management.enabled=true

greeting.message=Hello
greeting.name=quarkus
