%dev.quarkus.http.host=0.0.0.0
%dev.quarkus.http.port=8080
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=*
%dev.quarkus.dev-ui.cors.enabled=false
%dev.quarkus.kafka.devservices.enabled=false
%dev.quarkus.datasource.devservices.volumes."/"=/var/lib/postgresql/

# configure your datasource
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-database/person
%prod.quarkus.datasource.jdbc.driver=org.postgresql.Driver
%prod.quarkus.datasource.username=sa
%prod.quarkus.datasource.password=sa
%prod.quarkus.hibernate-orm.database.generation=drop-and-create
%prod.quarkus.hibernate-orm.sql-load-script=import.sql

# OpenShift extension
%prod.quarkus.kubernetes-client.trust-certs=true
%prod.quarkus.kubernetes.deploy=true
%prod.quarkus.kubernetes.deployment-target=openshift
%prod.quarkus.openshift.build-strategy=docker
%prod.quarkus.openshift.route.expose=true
%prod.quarkus.openshift.route.target-port=http
%prod.quarkus.openshift.route.tls.termination=edge
%prod.quarkus.openshift.route.tls.insecure-edge-termination-policy=None
quarkus.openshift.deployment-kind=Deployment
quarkus.container-image.group=USERXX-project
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000